// All NSE-listed companies — symbol + full name for Stock Analysis search
// 500+ stocks covering all major indices and sectors

export const ALL_STOCKS = [
  // NIFTY 50
  { s:'RELIANCE',    name:'Reliance Industries Ltd',        sector:'Energy' },
  { s:'TCS',         name:'Tata Consultancy Services',      sector:'IT' },
  { s:'HDFCBANK',    name:'HDFC Bank Ltd',                  sector:'Banking' },
  { s:'INFY',        name:'Infosys Ltd',                    sector:'IT' },
  { s:'ICICIBANK',   name:'ICICI Bank Ltd',                 sector:'Banking' },
  { s:'HINDUNILVR',  name:'Hindustan Unilever Ltd',         sector:'FMCG' },
  { s:'SBIN',        name:'State Bank of India',            sector:'Banking' },
  { s:'BHARTIARTL',  name:'Bharti Airtel Ltd',              sector:'Telecom' },
  { s:'BAJFINANCE',  name:'Bajaj Finance Ltd',              sector:'NBFC' },
  { s:'KOTAKBANK',   name:'Kotak Mahindra Bank',            sector:'Banking' },
  { s:'LT',          name:'Larsen & Toubro Ltd',            sector:'Infrastructure' },
  { s:'WIPRO',       name:'Wipro Ltd',                      sector:'IT' },
  { s:'HCLTECH',     name:'HCL Technologies Ltd',           sector:'IT' },
  { s:'AXISBANK',    name:'Axis Bank Ltd',                  sector:'Banking' },
  { s:'ASIANPAINT',  name:'Asian Paints Ltd',               sector:'Chemicals' },
  { s:'MARUTI',      name:'Maruti Suzuki India Ltd',        sector:'Auto' },
  { s:'SUNPHARMA',   name:'Sun Pharmaceutical Industries',  sector:'Pharma' },
  { s:'TITAN',       name:'Titan Company Ltd',              sector:'Consumer' },
  { s:'NESTLEIND',   name:'Nestle India Ltd',               sector:'FMCG' },
  { s:'ULTRACEMCO',  name:'UltraTech Cement Ltd',           sector:'Cement' },
  { s:'NTPC',        name:'NTPC Ltd',                       sector:'Power' },
  { s:'POWERGRID',   name:'Power Grid Corp of India',       sector:'Power' },
  { s:'ADANIENT',    name:'Adani Enterprises Ltd',          sector:'Conglomerate' },
  { s:'ADANIPORTS',  name:'Adani Ports & SEZ Ltd',          sector:'Logistics' },
  { s:'ONGC',        name:'Oil & Natural Gas Corp',         sector:'Energy' },
  { s:'COALINDIA',   name:'Coal India Ltd',                 sector:'Mining' },
  { s:'HINDALCO',    name:'Hindalco Industries Ltd',        sector:'Metals' },
  { s:'JSWSTEEL',    name:'JSW Steel Ltd',                  sector:'Metals' },
  { s:'TATASTEEL',   name:'Tata Steel Ltd',                 sector:'Metals' },
  { s:'TATAMOTORS',  name:'Tata Motors Ltd',                sector:'Auto' },
  { s:'M&M',         name:'Mahindra & Mahindra Ltd',        sector:'Auto' },
  { s:'BAJAJFINSV',  name:'Bajaj Finserv Ltd',              sector:'Finance' },
  { s:'BAJAJ-AUTO',  name:'Bajaj Auto Ltd',                 sector:'Auto' },
  { s:'TECHM',       name:'Tech Mahindra Ltd',              sector:'IT' },
  { s:'DIVISLAB',    name:'Divi\'s Laboratories Ltd',       sector:'Pharma' },
  { s:'DRREDDY',     name:'Dr Reddy\'s Laboratories',       sector:'Pharma' },
  { s:'CIPLA',       name:'Cipla Ltd',                      sector:'Pharma' },
  { s:'EICHERMOT',   name:'Eicher Motors Ltd',              sector:'Auto' },
  { s:'HEROMOTOCO',  name:'Hero MotoCorp Ltd',              sector:'Auto' },
  { s:'INDUSINDBK',  name:'IndusInd Bank Ltd',              sector:'Banking' },
  { s:'GRASIM',      name:'Grasim Industries Ltd',          sector:'Diversified' },
  { s:'TATACONSUM',  name:'Tata Consumer Products',         sector:'FMCG' },
  { s:'BRITANNIA',   name:'Britannia Industries Ltd',       sector:'FMCG' },
  { s:'BPCL',        name:'Bharat Petroleum Corp',          sector:'Energy' },
  { s:'IOC',         name:'Indian Oil Corp Ltd',            sector:'Energy' },
  // NIFTY NEXT 50
  { s:'ADANIGREEN',  name:'Adani Green Energy Ltd',         sector:'Renewable Energy' },
  { s:'ADANITRANS',  name:'Adani Transmission Ltd',         sector:'Power' },
  { s:'ATGL',        name:'Adani Total Gas Ltd',            sector:'Utilities' },
  { s:'AMBUJACEM',   name:'Ambuja Cements Ltd',             sector:'Cement' },
  { s:'APOLLOHOSP',  name:'Apollo Hospitals Enterprise',    sector:'Healthcare' },
  { s:'AUROPHARMA',  name:'Aurobindo Pharma Ltd',           sector:'Pharma' },
  { s:'BANDHANBNK',  name:'Bandhan Bank Ltd',               sector:'Banking' },
  { s:'BANKBARODA',  name:'Bank of Baroda',                 sector:'Banking' },
  { s:'BERGEPAINT',  name:'Berger Paints India Ltd',        sector:'Chemicals' },
  { s:'BIOCON',      name:'Biocon Ltd',                     sector:'Pharma' },
  { s:'BOSCHLTD',    name:'Bosch Ltd',                      sector:'Auto Ancillary' },
  { s:'CANBK',       name:'Canara Bank',                    sector:'Banking' },
  { s:'CHOLAFIN',    name:'Cholamandalam Investment',       sector:'NBFC' },
  { s:'COLPAL',      name:'Colgate-Palmolive India',        sector:'FMCG' },
  { s:'CONCOR',      name:'Container Corp of India',        sector:'Logistics' },
  { s:'COROMANDEL',  name:'Coromandel International',       sector:'Agri' },
  { s:'CUB',         name:'City Union Bank Ltd',            sector:'Banking' },
  { s:'DABUR',       name:'Dabur India Ltd',                sector:'FMCG' },
  { s:'DALBHARAT',   name:'Dalmia Bharat Ltd',              sector:'Cement' },
  { s:'DEEPAKNTR',   name:'Deepak Nitrite Ltd',             sector:'Chemicals' },
  { s:'DELTACORP',   name:'Delta Corp Ltd',                 sector:'Hospitality' },
  { s:'ESCORTS',     name:'Escorts Kubota Ltd',             sector:'Agri Equipment' },
  { s:'GAIL',        name:'GAIL India Ltd',                 sector:'Gas' },
  { s:'GODREJCP',    name:'Godrej Consumer Products',       sector:'FMCG' },
  { s:'GODREJPROP',  name:'Godrej Properties Ltd',          sector:'Real Estate' },
  { s:'HDFCLIFE',    name:'HDFC Life Insurance',            sector:'Insurance' },
  { s:'HAL',         name:'Hindustan Aeronautics Ltd',      sector:'Defence' },
  { s:'HAVELLS',     name:'Havells India Ltd',              sector:'Electricals' },
  { s:'IDFCFIRSTB',  name:'IDFC First Bank Ltd',            sector:'Banking' },
  { s:'ICICIGI',     name:'ICICI Lombard General Insurance',sector:'Insurance' },
  { s:'ICICIPRULI',  name:'ICICI Prudential Life Insurance',sector:'Insurance' },
  { s:'IGL',         name:'Indraprastha Gas Ltd',           sector:'Gas' },
  { s:'INDUSTOWER',  name:'Indus Towers Ltd',               sector:'Telecom Infra' },
  { s:'IRCTC',       name:'Indian Railway Catering & Tourism',sector:'Travel' },
  { s:'LICI',        name:'Life Insurance Corp of India',   sector:'Insurance' },
  { s:'LUPIN',       name:'Lupin Ltd',                      sector:'Pharma' },
  { s:'MARICO',      name:'Marico Ltd',                     sector:'FMCG' },
  { s:'MCDOWELL-N',  name:'United Spirits Ltd',             sector:'Beverages' },
  { s:'MPHASIS',     name:'Mphasis Ltd',                    sector:'IT' },
  { s:'MUTHOOTFIN',  name:'Muthoot Finance Ltd',            sector:'NBFC' },
  { s:'NAUKRI',      name:'Info Edge India Ltd',            sector:'Internet' },
  { s:'NMDC',        name:'NMDC Ltd',                       sector:'Mining' },
  { s:'OFSS',        name:'Oracle Financial Services',      sector:'IT' },
  { s:'PAGEIND',     name:'Page Industries Ltd',            sector:'Textile' },
  { s:'PEL',         name:'Piramal Enterprises Ltd',        sector:'Finance' },
  { s:'PERSISTENT',  name:'Persistent Systems Ltd',         sector:'IT' },
  { s:'PETRONET',    name:'Petronet LNG Ltd',               sector:'Energy' },
  { s:'PIDILITIND',  name:'Pidilite Industries Ltd',        sector:'Chemicals' },
  { s:'PNB',         name:'Punjab National Bank',           sector:'Banking' },
  { s:'POLYCAB',     name:'Polycab India Ltd',              sector:'Electricals' },
  { s:'SBICARD',     name:'SBI Cards & Payment Services',   sector:'Finance' },
  { s:'SBILIFE',     name:'SBI Life Insurance',             sector:'Insurance' },
  { s:'SHREECEM',    name:'Shree Cement Ltd',               sector:'Cement' },
  { s:'SIEMENS',     name:'Siemens Ltd',                    sector:'Industrials' },
  { s:'TATACOMM',    name:'Tata Communications Ltd',        sector:'Telecom' },
  { s:'TATAPOWER',   name:'Tata Power Co Ltd',              sector:'Power' },
  { s:'TORNTPHARM', name:'Torrent Pharmaceuticals',         sector:'Pharma' },
  { s:'TORNTPOWER',  name:'Torrent Power Ltd',              sector:'Power' },
  { s:'TRENT',       name:'Trent Ltd',                      sector:'Retail' },
  { s:'UBL',         name:'United Breweries Ltd',           sector:'Beverages' },
  { s:'UPL',         name:'UPL Ltd',                        sector:'Agri' },
  { s:'VEDL',        name:'Vedanta Ltd',                    sector:'Metals' },
  { s:'VOLTAS',      name:'Voltas Ltd',                     sector:'Electricals' },
  { s:'ZYDUSLIFE',   name:'Zydus Lifesciences Ltd',         sector:'Pharma' },
  // Mid Cap notable
  { s:'ABCAPITAL',   name:'Aditya Birla Capital Ltd',       sector:'Finance' },
  { s:'ABFRL',       name:'Aditya Birla Fashion & Retail',  sector:'Retail' },
  { s:'AEGISLOG',    name:'Aegis Logistics Ltd',            sector:'Logistics' },
  { s:'ALKYLAMINE',  name:'Alkyl Amines Chemicals Ltd',     sector:'Chemicals' },
  { s:'ALKEM',       name:'Alkem Laboratories Ltd',         sector:'Pharma' },
  { s:'APLLTD',      name:'Alembic Pharmaceuticals',        sector:'Pharma' },
  { s:'ASTRAL',      name:'Astral Ltd',                     sector:'Pipes' },
  { s:'ATUL',        name:'Atul Ltd',                       sector:'Chemicals' },
  { s:'BALRAMCHIN',  name:'Balrampur Chini Mills Ltd',      sector:'Sugar' },
  { s:'BATAINDIA',   name:'Bata India Ltd',                 sector:'Consumer' },
  { s:'BEL',         name:'Bharat Electronics Ltd',         sector:'Defence' },
  { s:'BHEL',        name:'Bharat Heavy Electricals Ltd',   sector:'Engineering' },
  { s:'BLUEDART',    name:'Blue Dart Express Ltd',          sector:'Logistics' },
  { s:'CAMS',        name:'Computer Age Mgmt Services',     sector:'Finance' },
  { s:'CASTROLIND',  name:'Castrol India Ltd',              sector:'Oil' },
  { s:'CENTURYTEX',  name:'Century Textiles & Industries',  sector:'Textile' },
  { s:'CHAMBLFERT',  name:'Chambal Fertilisers & Chemicals',sector:'Agri' },
  { s:'CROMPTON',    name:'Crompton Greaves Consumer',      sector:'Electricals' },
  { s:'CUMMINSIND',  name:'Cummins India Ltd',              sector:'Engineering' },
  { s:'DMART',       name:'Avenue Supermarts Ltd (DMart)',   sector:'Retail' },
  { s:'EDELWEISS',   name:'Edelweiss Financial Services',   sector:'Finance' },
  { s:'EIHOTEL',     name:'EIH Ltd (Oberoi Hotels)',         sector:'Hospitality' },
  { s:'EMAMILTD',    name:'Emami Ltd',                      sector:'FMCG' },
  { s:'ENDURANCE',   name:'Endurance Technologies Ltd',     sector:'Auto Ancillary' },
  { s:'ENGINERSIN',  name:'Engineers India Ltd',            sector:'Engineering' },
  { s:'EQUITASBNK',  name:'Equitas Small Finance Bank',     sector:'Banking' },
  { s:'FEDERALBNK',  name:'Federal Bank Ltd',               sector:'Banking' },
  { s:'FINCABLES',   name:'Finolex Cables Ltd',             sector:'Electricals' },
  { s:'FINPIPE',     name:'Finolex Industries Ltd',         sector:'Pipes' },
  { s:'FORTIS',      name:'Fortis Healthcare Ltd',          sector:'Healthcare' },
  { s:'GLENMARK',    name:'Glenmark Pharmaceuticals',       sector:'Pharma' },
  { s:'GMRAIRPORT',  name:'GMR Airports Infrastructure',    sector:'Infrastructure' },
  { s:'GNFC',        name:'Gujarat Narmada Valley Fertilizers',sector:'Chemicals' },
  { s:'GRANULES',    name:'Granules India Ltd',             sector:'Pharma' },
  { s:'GSFC',        name:'Gujarat State Fertilizers & Chemicals',sector:'Chemicals' },
  { s:'HFCL',        name:'HFCL Ltd',                       sector:'Telecom Infra' },
  { s:'HIKAL',       name:'Hikal Ltd',                      sector:'Chemicals' },
  { s:'HONAUT',      name:'Honeywell Automation India',     sector:'Industrials' },
  { s:'HUDCO',       name:'Housing & Urban Dev Corp',       sector:'Finance' },
  { s:'IDBI',        name:'IDBI Bank Ltd',                  sector:'Banking' },
  { s:'IFBIND',      name:'IFB Industries Ltd',             sector:'Consumer Durables' },
  { s:'IEX',         name:'Indian Energy Exchange Ltd',     sector:'Power' },
  { s:'IIFL',        name:'IIFL Finance Ltd',               sector:'NBFC' },
  { s:'IPCALAB',     name:'IPCA Laboratories Ltd',          sector:'Pharma' },
  { s:'IRB',         name:'IRB Infrastructure Developers',  sector:'Infrastructure' },
  { s:'JKCEMENT',    name:'JK Cement Ltd',                  sector:'Cement' },
  { s:'JKLAKSHMI',   name:'JK Lakshmi Cement Ltd',          sector:'Cement' },
  { s:'JKPAPER',     name:'JK Paper Ltd',                   sector:'Paper' },
  { s:'JUBLFOOD',    name:'Jubilant Foodworks Ltd',         sector:'QSR' },
  { s:'KANSAINER',   name:'Kansai Nerolac Paints',          sector:'Chemicals' },
  { s:'KARURVYSYA',  name:'Karur Vysya Bank Ltd',           sector:'Banking' },
  { s:'KEC',         name:'KEC International Ltd',          sector:'Engineering' },
  { s:'KPITTECH',    name:'KPIT Technologies Ltd',          sector:'IT' },
  { s:'KRBL',        name:'KRBL Ltd',                       sector:'FMCG' },
  { s:'L&TFH',       name:'L&T Finance Holdings Ltd',       sector:'NBFC' },
  { s:'LALPATHLAB',  name:'Dr Lal PathLabs Ltd',            sector:'Healthcare' },
  { s:'LICHSGFIN',   name:'LIC Housing Finance Ltd',        sector:'NBFC' },
  { s:'LINDEINDIA',  name:'Linde India Ltd',                sector:'Chemicals' },
  { s:'LTIM',        name:'LTIMindtree Ltd',                sector:'IT' },
  { s:'LTTS',        name:'L&T Technology Services',        sector:'IT' },
  { s:'MANAPPURAM', name:'Manappuram Finance Ltd',          sector:'NBFC' },
  { s:'MAPMYINDIA',  name:'C.E. Info Systems (MapMyIndia)', sector:'Technology' },
  { s:'MAXHEALTH',   name:'Max Healthcare Institute',       sector:'Healthcare' },
  { s:'MCX',         name:'Multi Commodity Exchange of India',sector:'Exchange' },
  { s:'METROPOLIS',  name:'Metropolis Healthcare Ltd',      sector:'Healthcare' },
  { s:'MINDTREE',    name:'MindTree Ltd',                   sector:'IT' },
  { s:'MRF',         name:'MRF Ltd',                        sector:'Auto Ancillary' },
  { s:'NATIONALUM',  name:'National Aluminium Co Ltd',      sector:'Metals' },
  { s:'NAM-INDIA',   name:'Nippon India Mutual Fund',       sector:'Finance' },
  { s:'NAVINFLUOR',  name:'Navin Fluorine International',   sector:'Chemicals' },
  { s:'NBCC',        name:'NBCC India Ltd',                 sector:'Real Estate' },
  { s:'NH',          name:'Narayana Hrudayalaya Ltd',       sector:'Healthcare' },
  { s:'NIITLTD',     name:'NIIT Ltd',                       sector:'Education' },
  { s:'NILKAMAL',    name:'Nilkamal Ltd',                   sector:'Consumer' },
  { s:'NLC',         name:'NLC India Ltd',                  sector:'Power' },
  { s:'NSLNISP',     name:'NMDC Steel Ltd',                 sector:'Steel' },
  { s:'OBEROIRLTY',  name:'Oberoi Realty Ltd',              sector:'Real Estate' },
  { s:'PCBL',        name:'PCBL Ltd',                       sector:'Chemicals' },
  { s:'PFIZER',      name:'Pfizer Ltd',                     sector:'Pharma' },
  { s:'PHOENIXLTD',  name:'Phoenix Mills Ltd',              sector:'Real Estate' },
  { s:'PFC',         name:'Power Finance Corp Ltd',         sector:'Finance' },
  { s:'RECLTD',      name:'REC Ltd',                        sector:'Finance' },
  { s:'RELAXO',      name:'Relaxo Footwears Ltd',           sector:'Consumer' },
  { s:'RITES',       name:'RITES Ltd',                      sector:'Engineering' },
  { s:'SAFARI',      name:'Safari Industries India Ltd',    sector:'Consumer' },
  { s:'SAIL',        name:'Steel Authority of India',       sector:'Steel' },
  { s:'SANOFI',      name:'Sanofi India Ltd',               sector:'Pharma' },
  { s:'SCHAEFFLER',  name:'Schaeffler India Ltd',           sector:'Auto Ancillary' },
  { s:'SHYAMMETL',   name:'Shyam Metalics & Energy',        sector:'Metals' },
  { s:'SKFINDIA',    name:'SKF India Ltd',                  sector:'Industrials' },
  { s:'SOBHA',       name:'Sobha Ltd',                      sector:'Real Estate' },
  { s:'SONACOMS',    name:'Sona BLW Precision Forgings',    sector:'Auto Ancillary' },
  { s:'STARHEALTH',  name:'Star Health & Allied Insurance', sector:'Insurance' },
  { s:'SUDARSCHEM',  name:'Sudarshan Chemical Industries',  sector:'Chemicals' },
  { s:'SUMICHEM',    name:'Sumitomo Chemical India',        sector:'Agri' },
  { s:'SUNDARMFIN',  name:'Sundaram Finance Ltd',           sector:'NBFC' },
  { s:'SUNDRMBRAK',  name:'Sundram Fasteners Ltd',          sector:'Auto Ancillary' },
  { s:'SUPREMEIND',  name:'Supreme Industries Ltd',         sector:'Plastics' },
  { s:'SUVENPHAR',   name:'Suven Pharmaceuticals Ltd',      sector:'Pharma' },
  { s:'SYMPHONY',    name:'Symphony Ltd',                   sector:'Consumer Durables' },
  { s:'TATACHEM',    name:'Tata Chemicals Ltd',             sector:'Chemicals' },
  { s:'TATAELXSI',   name:'Tata Elxsi Ltd',                 sector:'IT' },
  { s:'TEAMLEASE',   name:'TeamLease Services Ltd',         sector:'Staffing' },
  { s:'THYROCARE',   name:'Thyrocare Technologies Ltd',     sector:'Healthcare' },
  { s:'TIMKEN',      name:'Timken India Ltd',               sector:'Industrials' },
  { s:'TRIDENT',     name:'Trident Ltd',                    sector:'Textile' },
  { s:'TTKPRESTIG',  name:'TTK Prestige Ltd',               sector:'Consumer Durables' },
  { s:'TV18BRDCST',  name:'TV18 Broadcast Ltd',             sector:'Media' },
  { s:'TVSMOTOR',    name:'TVS Motor Company Ltd',          sector:'Auto' },
  { s:'UBLLTD',      name:'UBL Ltd',                        sector:'Beverages' },
  { s:'UJJIVANSFB',  name:'Ujjivan Small Finance Bank',     sector:'Banking' },
  { s:'VAIBHAVGBL',  name:'Vaibhav Global Ltd',             sector:'Retail' },
  { s:'VGUARD',      name:'V-Guard Industries Ltd',         sector:'Electricals' },
  { s:'VIPIND',      name:'VIP Industries Ltd',             sector:'Consumer' },
  { s:'VSTIND',      name:'VST Industries Ltd',             sector:'Tobacco' },
  { s:'WHIRLPOOL',   name:'Whirlpool of India Ltd',         sector:'Consumer Durables' },
  { s:'WIPRO',       name:'Wipro Ltd',                      sector:'IT' },
  { s:'WOCKPHARMA',  name:'Wockhardt Ltd',                  sector:'Pharma' },
  { s:'YESBANK',     name:'Yes Bank Ltd',                   sector:'Banking' },
  { s:'ZEEL',        name:'Zee Entertainment Enterprises',  sector:'Media' },
  { s:'ZOMATO',      name:'Zomato Ltd',                     sector:'Internet' },
  { s:'PAYTM',       name:'One97 Communications (Paytm)',   sector:'Fintech' },
  { s:'NYKAA',       name:'FSN E-Commerce Ventures (Nykaa)',sector:'Retail' },
  { s:'DELHIVERY',   name:'Delhivery Ltd',                  sector:'Logistics' },
  { s:'POLICYBZR',   name:'PB Fintech (PolicyBazaar)',      sector:'Fintech' },
  { s:'CARTRADE',    name:'CarTrade Tech Ltd',              sector:'Internet' },
  { s:'LATENTVIEW',  name:'LatentView Analytics Ltd',       sector:'IT' },
  { s:'HLEGLAS',     name:'HLE Glascoat Ltd',               sector:'Engineering' },
  { s:'MEDANTA',     name:'Global Health Ltd (Medanta)',    sector:'Healthcare' },
  { s:'CAMPUS',      name:'Campus Activewear Ltd',          sector:'Consumer' },
  { s:'BIKAJI',      name:'Bikaji Foods International',     sector:'FMCG' },
  { s:'KAYNES',      name:'Kaynes Technology India Ltd',    sector:'Electronics' },
  { s:'SYRMA',       name:'Syrma SGS Technology Ltd',       sector:'Electronics' },
  { s:'IDEAFORGE',   name:'ideaForge Technology Ltd',       sector:'Defence Tech' },
  { s:'SULA',        name:'Sula Vineyards Ltd',             sector:'Beverages' },
  { s:'SENCO',       name:'Senco Gold Ltd',                 sector:'Jewellery' },
  { s:'YATHARTH',    name:'Yatharth Hospital & Trauma',     sector:'Healthcare' },
  // Indices (for reference in analysis)
  { s:'NIFTY50',     name:'Nifty 50 Index',                 sector:'Index' },
  { s:'BANKNIFTY',   name:'Bank Nifty Index',               sector:'Index' },
  { s:'FINNIFTY',    name:'Nifty Financial Services Index', sector:'Index' },
  { s:'MIDCPNIFTY',  name:'Nifty Midcap Select Index',      sector:'Index' },
]

export const SECTORS = [...new Set(ALL_STOCKS.map(s => s.sector))].sort()
